# Generated by Django 5.2.6 on 2025-10-04 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='miss_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
